model: stormer

framework: pytorch

workflow:
  generate_data: True
  train: False
  checkpoint: False
  debug: False

# dataset:
#   data_folder: data/stormer-1G/
#   format: hdf5
#   num_files_train: 2920
#   num_samples_per_file: 1
#   record_length: 1104691456 # stormer load two files at once

dataset:
  data_folder: /lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/data/stormer
  # data_folder: /local/scratch
  format: hdf5
  num_files_train: 2920
  # num_files_train: 40
  # num_files_train: 1460
  num_samples_per_file: 1
  # record_length: 1104691456
  record_length: 1104764644
  record_length_resize: 574619648
  # record_length_resize: 599014128
  # record_length_resize: 750014128
  enable_chunking: True
  chunk_2d_dim: [16619, 33238]
  # chunk_2d_dim: [16618, 33236]

reader:
  data_loader: pytorch
  batch_size: 1
  read_threads: 4
  # read_threads: 6
  file_shuffle: seed
  # preprocess_time: 1.75874
  # preprocess_time: 1.69874
  # preprocess_time_stdev: 0.11346
  # preprocess_time: 1.42381
  # preprocess_time_stdev: 0.06665
  preprocess_time: 0.5638 
  preprocess_time_stdev: 0.0088
  transformed_sample: [3, 16619, 33238]
  prefetch_size: 10

train:
  epochs: 1
  computation_time: 0.789605
  computation_time_stdev: 0.341226
  # total_training_steps: 10
